# Curso Numpy - IA Academy

## Importar bibliotecas

In [86]:
import numpy as np
from rich import print as rprint
import sys
import random

In [63]:
rprint(f"Versão do Python: {sys.version}")
rprint(f"Versão do Numpy: {np.__version__}")

Versão do Python: 3.13.5 (main, Aug  5 2025, 17:25:48) [GCC 11.4.0]

Versão do Numpy: 2.3.2

## Numpy x Listas

### Tamanho Fixo

In [64]:
# Listas

list_a = [1, 2, 3, 4]

rprint(f"Lista: {list_a}")
rprint(f"Tipo: {type(list_a)}")
rprint(f"Id: {id(list_a)}")
# Adicionando um elemento
list_a.append(5)
rprint(f"Adicionando um elemento: {list_a}")
# O id não é alterado
rprint(f"Id: {id(list_a)}")


Lista: [1, 2, 3, 4]

Tipo: <class 'list'>

Id: 126683998482048

Adicionando um elemento: [1, 2, 3, 4, 5]

Id: 126683998482048

In [65]:
# Numpy

array_a = np.array([1, 2, 3, 4])

rprint(f"Array: {array_a}")
rprint(f"Tipo: {type(array_a)}")
rprint(f"Id: {id(array_a)}")
# Adicionando um elemento
array_a = np.append(array_a, [5])
rprint(f"Adicionando um elemento: {array_a}")
# O id é alterado
rprint(f"Id: {id(array_a)}")


Array: [1 2 3 4]

Tipo: <class 'numpy.ndarray'>

Id: 126682835673104

Adicionando um elemento: [1 2 3 4 5]

Id: 126682832938896

### Tipos de dados

In [66]:
# Listas

list_a = [1, 2.4, 'a', True, 5]

rprint(f"Lista: {list_a}")
rprint(f"Tipo: {type(list_a)}")
rprint(f"Id: {id(list_a)}")
# Acessando os tipo de dados da lista
rprint(f"Acessando os tipo de dados da lista")
for i in list_a:
    rprint(f"Tipo: {type(i)}")
# Adicionando um elemento
list_a.append(None)
rprint(f"Adicionando um elemento: {list_a}")
# O id não é alterado
rprint(f"Id: {id(list_a)}")
# Acessando os tipo de dados da lista
rprint(f"Acessando os tipo de dados da lista")
for i in list_a:
    rprint(f"Tipo: {type(i)}")


Lista: [1, 2.4, 'a', True, 5]

Tipo: <class 'list'>

Id: 126684006870784

Acessando os tipo de dados da lista

Tipo: <class 'int'>

Tipo: <class 'float'>

Tipo: <class 'str'>

Tipo: <class 'bool'>

Tipo: <class 'int'>

Adicionando um elemento: [1, 2.4, 'a', True, 5, None]

Id: 126684006870784

Acessando os tipo de dados da lista

Tipo: <class 'int'>

Tipo: <class 'float'>

Tipo: <class 'str'>

Tipo: <class 'bool'>

Tipo: <class 'int'>

Tipo: <class 'NoneType'>

In [67]:
# Array

array_a = np.array(list_a)

rprint(f"Array: {array_a}")
rprint(f"Tipo: {type(array_a)}")
rprint(f"Id: {id(array_a)}")
# Acessando os tipo de dados da lista
rprint(f"Acessando os tipo de dados do array")
for i in array_a:
    rprint(f"Tipo: {type(i)}")
# Adicionando um elemento
array_a = np.append(array_a, [5])
rprint(f"Adicionando um elemento: {array_a}")
# O id é alterado
rprint(f"Id: {id(array_a)}")
# Acessando os tipo de dados da lista
rprint(f"Acessando os tipo de dados do array")
for i in array_a:
    rprint(f"Tipo: {type(i)}")
    
rprint(f"Tipo de dados do array: {array_a.dtype}")

Array: [1 2.4 'a' True 5 None]

Tipo: <class 'numpy.ndarray'>

Id: 126682835803216

Acessando os tipo de dados do array

Tipo: <class 'int'>

Tipo: <class 'float'>

Tipo: <class 'str'>

Tipo: <class 'bool'>

Tipo: <class 'int'>

Tipo: <class 'NoneType'>

Adicionando um elemento: [1 2.4 'a' True 5 None 5]

Id: 126682835680304

Acessando os tipo de dados do array

Tipo: <class 'int'>

Tipo: <class 'float'>

Tipo: <class 'str'>

Tipo: <class 'bool'>

Tipo: <class 'int'>

Tipo: <class 'NoneType'>

Tipo: <class 'int'>

Tipo de dados do array: object

### Vetorização

In [68]:
# Cálculos aritméticos com listas
list_a = [1, 2, 3, 4, 5]
list_b = [6, 7, 8, 9, 10]

# list_c = [i + j for i, j in zip(list_a, list_b)]
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] + list_b[i])

rprint(f"Lista c: {list_c}")

# Cálculos aritméticos com arrays
array_a = np.array(list_a)
array_b = np.array(list_b)
array_c = array_a + array_b

rprint(f"Array c: {array_c}")

# Outros cálculos aritméticos com arrays
array_d = array_a * array_b
rprint(f"Array d: {array_d}")

array_e = array_a / array_b
rprint(f"Array e: {array_e}")

array_f = array_a ** array_b
rprint(f"Array f: {array_f}")

array_g = array_a % array_b
rprint(f"Array g: {array_g}")

array_h = array_a // array_b
rprint(f"Array h: {array_h}")

array_i = array_a ** 0.5
rprint(f"Array i: {array_i}")

array_j = np.sqrt(array_a)
rprint(f"Array j: {array_j}")

array_k = np.log(array_a)
rprint(f"Array k: {array_k}")

array_l = np.exp(array_a)
rprint(f"Array l: {array_l}")

array_m = np.sin(array_a)
rprint(f"Array m: {array_m}")

array_n = np.cos(array_a)
rprint(f"Array n: {array_n}")

array_o = np.tan(array_a)
rprint(f"Array o: {array_o}")


Lista c: [7, 9, 11, 13, 15]

Array c: [ 7  9 11 13 15]

Array d: [ 6 14 24 36 50]

Array e: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]

Array f: [      1     128    6561  262144 9765625]

Array g: [1 2 3 4 5]

Array h: [0 0 0 0 0]

Array i: [1.         1.41421356 1.73205081 2.         2.23606798]

Array j: [1.         1.41421356 1.73205081 2.         2.23606798]

Array k: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Array l: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Array m: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Array n: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

Array o: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]

### Broadcasting

In [69]:
# Listas
list_a = [1, 2, 3, 4, 5]

try:
    list_a + 5 # Gerará um erro de tipo
except TypeError as e:
    rprint(f"Erro: {e}")


# Uma forma eficaz de calcular esta soma

list_b = []
for i in list_a:
    list_b.append(i + 5)
    
rprint(f"Lista b: {list_b}")

Erro: can only concatenate list (not "int") to list

Lista b: [6, 7, 8, 9, 10]

In [70]:
# Arrays

array_a = np.array(list_a)
rprint(f"Array a: {array_a}")
array_b = array_a + 5
rprint(f"Array b: {array_b}")

array_c = np.array([[5], [10]])
rprint(f"Array c: {array_c}")
rprint(f"Array c Shape: {array_c.shape}")

array_d = array_a + array_c
rprint(f"Array d: {array_d}")

array_tmp = np.array([[1, 2, 3], [4, 5, 6]])

try:
    array_e = array_d + array_tmp # Gerará um erro de valor
except ValueError as e:
    rprint(f"Erro: {e} - quantidade de colunas diferentes entre as matrizes")


Array a: [1 2 3 4 5]

Array b: [ 6  7  8  9 10]

Array c: [[ 5]
 [10]]

Array c Shape: (2, 1)

Array d: [[ 6  7  8  9 10]
 [11 12 13 14 15]]

Erro: operands could not be broadcast together with shapes (2,5) (2,3)  - quantidade de colunas diferentes entre as
matrizes

## ndarray e atributos

In [77]:
list_a = [1, 2, 3, 4, 5]
array_from_list = np.array(list_a)
rprint(f"Array from list: {array_from_list}")
rprint(array_from_list + 5)

tuple_a = (1, 2, 3, 4, 5)
array_from_tuple = np.array(tuple_a)
rprint(f"Array from tuple: {array_from_tuple}")
rprint(array_from_tuple + 6)

set_a = {1, 2, 3, 4, 5}
array_from_set = np.array(set_a)
rprint(f"Array from set: {array_from_set}")

try:
    rprint(array_from_set + 7)
except TypeError as e:
    rprint(f"Erro: {e}")
    
dict_a = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
array_from_dict = np.array(dict_a)
rprint(f"Array from dict: {array_from_dict}")

try:
    rprint(array_from_dict + 8)
except TypeError as e:
    rprint(f"Erro: {e}")

Array from list: [1 2 3 4 5]

[ 6  7  8  9 10]

Array from tuple: [1 2 3 4 5]

[ 7  8  9 10 11]

Array from set: {1, 2, 3, 4, 5}

Erro: unsupported operand type(s) for +: 'set' and 'int'

Array from dict: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

Erro: unsupported operand type(s) for +: 'dict' and 'int'

## Dimensões

In [ ]:
# Array de 1D = Vetor
array_1d = np.array([1, 2, 3, 4, 5])
rprint(f"Vetor:\n {array_1d}")

In [90]:
# Filtros
rprint(f"Pesquisar no vetor o valor: {random.choice(array_1d)}")

Pesquisar no vetor o valor: 5

In [92]:
rprint(f"Resultado: {array_1d[4]}")

Resultado: 5

In [ ]:
# Array de 2D = Matriz
array_2d = np.array(
    [
        [1,  2,  3,  4,  5],
        [6,  7,  8,  9,  10],
        [11, 12, 13, 14, 15]
    ]
)
rprint(f"Matriz 2D:\n {array_2d}")

In [96]:
# Filtros
rprint(f"Pesquisar na matriz 2d o valor: {random.randint(1, 15)}")

Pesquisar na matriz 2d o valor: 3

In [97]:
rprint(f"Resultado: {array_2d[0][2]}")

Resultado: 3

In [ ]:
# Array de N dimensões
array_3d = np.array(
    [
        [
            [1,  2,  3,  4,  5],
            [6,  7,  8,  9,  10],
            [11, 12, 13, 14, 15]
        ],
        [
            [16,  17,  18,  19,  20],
            [21,  22,  23,  24,  25],
            [26,  27,  28,  29,  30]
        ]
    ]
    
)
rprint(f"Matriz 3D (Tensor):\n {array_3d}")

In [98]:
# Filtros
rprint(f"Pesquisar na matriz 3d o valor: {random.randint(1, 30)}")

Pesquisar na matriz 3d o valor: 17

In [99]:
rprint(f"Resultado: {array_3d[1][0][1]}")

Resultado: 17

## Atributos do Array

In [ ]:
# Size
rprint(array_1d.size) # np.array([1, 2, 3, 4, 5]
rprint(array_2d.size)
"""
np.array(
    [
        [1,  2,  3,  4,  5],
        [6,  7,  8,  9,  10],
        [11, 12, 13, 14, 15]
    ]
)
"""
rprint(array_3d.size)
"""
np.array(
    [
        [
            [1,  2,  3,  4,  5],
            [6,  7,  8,  9,  10],
            [11, 12, 13, 14, 15]
        ],
        [
            [16,  17,  18,  19,  20],
            [21,  22,  23,  24,  25],
            [26,  27,  28,  29,  30]
        ]
    ]
    
)
"""

5

15

30

'\nnp.array(\n    [\n        [\n            [1,  2,  3,  4,  5],\n            [6,  7,  8,  9,  10],\n            [11, 12, 13, 14, 15]\n        ],\n        [\n            [16,  17,  18,  19,  20],\n            [21,  22,  23,  24,  25],\n            [26,  27,  28,  29,  30]\n        ]\n    ]\n\n)\n'

In [107]:
# Dimensões
rprint(array_1d.ndim) # 1D
rprint(array_2d.ndim) # 2D
rprint(array_3d.ndim) # 3D

1

2

3

In [ ]:
# Shape -> quantidade de linhas e colunas
rprint(array_1d.shape) # 5 linhas, 0 colunas
rprint(array_2d.shape) # 3 linhas, 5 colunas
rprint(array_3d.shape) # 2 matrizes, 3 linhas e 5 colunas cada

(5,)

(3, 5)

(2, 3, 5)

In [ ]:
# itemsize quantidade de bits
rprint(array_1d.itemsize)
rprint(array_2d.itemsize)
rprint(array_3d.itemsize)

8

8

8

In [114]:
# nbytes
rprint(f"Quantidade de bytes: {array_1d.nbytes} que equivale a array_1d.size * array_1d.itemsize: {array_1d.size * array_1d.itemsize}")
rprint(f"Quantidade de bytes: {array_2d.nbytes} que equivale a array_2d.size * array_2d.itemsize: {array_2d.size * array_2d.itemsize}")
rprint(f"Quantidade de bytes: {array_3d.nbytes} que equivale a array_3d.size * array_3d.itemsize: {array_3d.size * array_3d.itemsize}")

Quantidade de bytes: 40 que equivale a array_1d.size * array_1d.itemsize: 40

Quantidade de bytes: 120 que equivale a array_2d.size * array_2d.itemsize: 120

Quantidade de bytes: 240 que equivale a array_3d.size * array_3d.itemsize: 240

In [123]:
# dtypes
rprint(array_1d.dtype)
rprint(array_2d.dtype)
rprint(array_3d.dtype)

# Alterando
array_1d.dtype = np.int32
rprint(array_1d.dtype)
array_2d.dtype = np.float64
rprint(array_2d.dtype)
rprint(array_2d)

int32

float64

int64

int32

float64

[[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323 4.0e-323 4.4e-323 4.9e-323]
 [5.4e-323 5.9e-323 6.4e-323 6.9e-323 7.4e-323]]